### ISSUE TITLE
Add octaves

### ISSUE THREAD

**Issue by Dard-Neuman** [jon-myers/idtp#387] opened 2024-01-01 20:31 UTC
At some point, it would be good to add octaves beyond that which is showing. Here we might take advantage of the old bug that allowed the movement of a trajectory to octaves below (or above) that which is showing. I'm thinking again of Tansen Pandey's Todi and the ability to transcribe in the octave below the lowest octave being displayed.

**Comment by jon-myers** [comment] 2024-01-25 20:32
Closing, as this is duplicate of #224

**Comment by jon-myers** [comment] 2024-01-25 20:32
Closing, as this is duplicate of #224

**Closed by jon-myers** 2024-01-25 20:32 UTC
Labels: enhancement
